package frr

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/fdcastel/warp-router/internal/config"
)

const frrConfTemplate = `! Warp Router — FRR configuration
! Generated by 'warp apply'. Do not edit manually.

frr version 10
frr defaults traditional

hostname {{ .Hostname }}
log syslog informational
service integrated-vtysh-config
!
{{- range .StaticRoutes }}
ip route {{ .Prefix }} {{ .NextHop }}{{ if .Device }} {{ .Device }}{{ end }}{{ if .Table }} table {{ .Table }}{{ end }}
{{- end }}
!
{{- if .ECMP }}
! ECMP default route
ip route 0.0.0.0/0{{ range .ECMPNextHops }} nexthop {{ .NextHop }} {{ .Device }}{{ if .Weight }} weight {{ .Weight }}{{ end }}{{ end }}
{{- end }}
!
{{- if .PBR }}
! Policy-Based Routing
{{- range .PBRMaps }}
pbr-map {{ .Name }} seq {{ .Seq }}
 match src-ip {{ .MatchSrc }}
 set nexthop {{ .NextHop }}{{ if .Device }} {{ .Device }}{{ end }}
!
{{- end }}
{{- range .PBRInterfaces }}
interface {{ .Device }}
 pbr-policy {{ .MapName }}
!
{{- end }}
{{- end }}
{{- if .BFD }}
!
! BFD peers for WAN health
bfd
{{- range .BFDPeers }}
 peer {{ .Address }}
  detect-multiplier 3
  receive-interval 300
  transmit-interval 300
 !
{{- end }}
!
{{- end }}
line vty
!
`

type frrData struct {
	Hostname     string
	StaticRoutes []staticRoute
	ECMP         bool
	ECMPNextHops []ecmpNextHop
	PBR          bool
	PBRMaps      []pbrMap
	PBRInterfaces []pbrInterface
	BFD          bool
	BFDPeers     []bfdPeer
}

type staticRoute struct {
	Prefix  string
	NextHop string
	Device  string
	Table   string
}

type ecmpNextHop struct {
	NextHop string
	Device  string
	Weight  int
}

type pbrMap struct {
	Name     string
	Seq      int
	MatchSrc string
	NextHop  string
	Device   string
}

type pbrInterface struct {
	Device  string
	MapName string
}

type bfdPeer struct {
	Address string
}

// Render generates an frr.conf from the site config.
func Render(cfg *config.SiteConfig) (string, error) {
	data := frrData{
		Hostname: cfg.Hostname,
	}

	// Build interface lookup: name → Interface
	ifaceByName := make(map[string]config.Interface)
	for _, iface := range cfg.Interfaces {
		ifaceByName[iface.Name] = iface
	}

	// Collect WAN interfaces with gateways
	var wanInterfaces []config.Interface
	for _, iface := range cfg.Interfaces {
		if iface.Role == "wan" {
			wanInterfaces = append(wanInterfaces, iface)
		}
	}

	// ECMP
	if cfg.ECMP != nil && cfg.ECMP.Enabled && len(wanInterfaces) > 1 {
		data.ECMP = true
		for _, wan := range wanInterfaces {
			if wan.Gateway != "" {
				weight := wan.Weight
				if weight <= 0 {
					weight = 1
				}
				data.ECMPNextHops = append(data.ECMPNextHops, ecmpNextHop{
					NextHop: wan.Gateway,
					Device:  wan.Device,
					Weight:  weight,
				})
			}
		}
	} else {
		// Single WAN: static default route
		for _, wan := range wanInterfaces {
			if wan.Gateway != "" {
				data.StaticRoutes = append(data.StaticRoutes, staticRoute{
					Prefix:  "0.0.0.0/0",
					NextHop: wan.Gateway,
					Device:  wan.Device,
				})
			}
		}
	}

	// PBR rules
	if len(cfg.PBR) > 0 {
		data.PBR = true
		// Find LAN interfaces to attach PBR policies
		lanDevices := make(map[string]bool)
		for _, iface := range cfg.Interfaces {
			if iface.Role == "lan" {
				lanDevices[iface.Device] = true
			}
		}

		for i, rule := range cfg.PBR {
			targetIface, ok := ifaceByName[rule.Interface]
			if !ok {
				continue
			}
			data.PBRMaps = append(data.PBRMaps, pbrMap{
				Name:     rule.Name,
				Seq:      (i + 1) * 10,
				MatchSrc: rule.Source,
				NextHop:  targetIface.Gateway,
				Device:   targetIface.Device,
			})
		}

		// Attach PBR policy to LAN interfaces
		for _, iface := range cfg.Interfaces {
			if iface.Role == "lan" {
				// Attach first PBR map name (FRR supports one pbr-policy per iface)
				if len(data.PBRMaps) > 0 {
					data.PBRInterfaces = append(data.PBRInterfaces, pbrInterface{
						Device:  iface.Device,
						MapName: data.PBRMaps[0].Name,
					})
				}
			}
		}
	}

	// BFD peers for WAN gateways
	for _, wan := range wanInterfaces {
		if wan.Gateway != "" {
			data.BFD = true
			data.BFDPeers = append(data.BFDPeers, bfdPeer{Address: wan.Gateway})
		}
	}

	tmpl, err := template.New("frr.conf").Parse(frrConfTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing FRR template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing FRR template: %w", err)
	}

	return buf.String(), nil
}
