package sysctl

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/fdcastel/warp-router/internal/config"
)

const sysctlConfTemplate = `# Warp Router — sysctl settings
# Generated by 'warp apply'. Do not edit manually.

# Enable IPv4 forwarding
net.ipv4.ip_forward = 1

# Reverse path filtering (loose mode for multi-WAN ECMP)
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.all.rp_filter = 2

# Conntrack tuning
net.netfilter.nf_conntrack_max = {{ .ConntrackMax }}

# TCP SYN flood protection
net.ipv4.tcp_syncookies = 1

# Disable ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Ignore ICMP broadcast pings
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Log martian packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
`

type sysctlData struct {
	ConntrackMax int
}

// Render generates sysctl configuration from the site config.
func Render(cfg *config.SiteConfig) (string, error) {
	data := sysctlData{
		ConntrackMax: 262144, // default
	}

	if cfg.Sysctl != nil && cfg.Sysctl.ConntrackMax > 0 {
		data.ConntrackMax = cfg.Sysctl.ConntrackMax
	}

	tmpl, err := template.New("sysctl.conf").Parse(sysctlConfTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing sysctl template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing sysctl template: %w", err)
	}

	return buf.String(), nil
}
