package nftables

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/fdcastel/warp-router/internal/config"
)

const nftConfTemplate = `#!/usr/sbin/nft -f
# Warp Router — nftables ruleset
# Generated by 'warp apply'. Do not edit manually.

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        # Loopback
        iif "lo" accept

        # Established/related
        ct state established,related accept

        # ICMP
        ip protocol icmp accept

        # SSH (always allowed)
        tcp dport 22 accept

        # DHCP server
        udp dport { 67, 68 } accept

        # DNS
        tcp dport 53 accept
        udp dport 53 accept

        # BGP
        tcp dport 179 accept

        # BFD
        udp dport { 3784, 3785, 4784 } accept
{{- range .InputRules }}

        # Custom input rule{{ if .Comment }} — {{ .Comment }}{{ end }}
        {{ .Rule }}
{{- end }}

        # Log and drop
        log prefix "nft-input-drop: " counter drop
    }

    chain forward {
        type filter hook forward priority filter; policy drop;

        # Established/related
        ct state established,related accept
{{- range .ForwardRules }}

        # {{ .Comment }}
        {{ .Rule }}
{{- end }}

        # Log and drop
        log prefix "nft-forward-drop: " counter drop
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

table inet nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
{{- range .MasqueradeRules }}

        # Masquerade on {{ .Device }}
        oifname "{{ .Device }}" masquerade
{{- end }}
    }
}
`

type nftData struct {
	InputRules      []nftRule
	ForwardRules    []nftRule
	MasqueradeRules []masqueradeRule
}

type nftRule struct {
	Rule    string
	Comment string
}

type masqueradeRule struct {
	Device string
}

// Render generates an nftables.conf from the site config.
func Render(cfg *config.SiteConfig) (string, error) {
	data := nftData{}

	// Build zone → device mapping
	zoneDevices := make(map[string][]string)
	ifaceByName := make(map[string]config.Interface)
	for _, iface := range cfg.Interfaces {
		ifaceByName[iface.Name] = iface
	}

	if cfg.Firewall != nil {
		for _, zone := range cfg.Firewall.Zones {
			for _, ifName := range zone.Interfaces {
				if iface, ok := ifaceByName[ifName]; ok {
					zoneDevices[zone.Name] = append(zoneDevices[zone.Name], iface.Device)
				}
			}
		}

		// Forward rules
		for _, rule := range cfg.Firewall.ForwardRules {
			fromDevs := zoneDevices[rule.From]
			toDevs := zoneDevices[rule.To]

			for _, fromDev := range fromDevs {
				for _, toDev := range toDevs {
					nftRule := buildForwardRule(fromDev, toDev, rule)
					data.ForwardRules = append(data.ForwardRules, nftRule)
				}
			}
		}

		// Input rules
		for _, rule := range cfg.Firewall.InputRules {
			devs := zoneDevices[rule.Zone]
			for _, dev := range devs {
				nftRule := buildInputRule(dev, rule)
				data.InputRules = append(data.InputRules, nftRule)
			}
		}
	} else {
		// No firewall config: allow all LAN → WAN forwarding
		for _, iface := range cfg.Interfaces {
			if iface.Role == "lan" {
				data.ForwardRules = append(data.ForwardRules, nftRule{
					Rule:    fmt.Sprintf(`iifname "%s" accept`, iface.Device),
					Comment: fmt.Sprintf("Allow all from %s (LAN)", iface.Name),
				})
			}
		}
	}

	// Masquerade on all WAN interfaces
	for _, iface := range cfg.Interfaces {
		if iface.Role == "wan" {
			data.MasqueradeRules = append(data.MasqueradeRules, masqueradeRule{
				Device: iface.Device,
			})
		}
	}

	tmpl, err := template.New("nftables.conf").Parse(nftConfTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing nftables template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing nftables template: %w", err)
	}

	return buf.String(), nil
}

func buildForwardRule(fromDev, toDev string, rule config.ForwardRule) nftRule {
	var parts []string
	parts = append(parts, fmt.Sprintf(`iifname "%s"`, fromDev))
	parts = append(parts, fmt.Sprintf(`oifname "%s"`, toDev))

	if rule.Protocol != "" {
		parts = append(parts, fmt.Sprintf("ip protocol %s", rule.Protocol))
	}
	if rule.Port != "" && rule.Protocol != "" {
		parts = append(parts, fmt.Sprintf("%s dport %s", rule.Protocol, rule.Port))
	}
	if rule.Source != "" {
		parts = append(parts, fmt.Sprintf("ip saddr %s", rule.Source))
	}
	if rule.Dest != "" {
		parts = append(parts, fmt.Sprintf("ip daddr %s", rule.Dest))
	}
	parts = append(parts, rule.Action)

	ruleStr := ""
	for i, p := range parts {
		if i > 0 {
			ruleStr += " "
		}
		ruleStr += p
	}

	comment := fmt.Sprintf("%s → %s: %s", rule.From, rule.To, rule.Action)
	return nftRule{Rule: ruleStr, Comment: comment}
}

func buildInputRule(dev string, rule config.InputRule) nftRule {
	var parts []string
	parts = append(parts, fmt.Sprintf(`iifname "%s"`, dev))

	if rule.Protocol != "" {
		parts = append(parts, fmt.Sprintf("ip protocol %s", rule.Protocol))
	}
	if rule.Port != "" && rule.Protocol != "" {
		parts = append(parts, fmt.Sprintf("%s dport %s", rule.Protocol, rule.Port))
	}
	if rule.Source != "" {
		parts = append(parts, fmt.Sprintf("ip saddr %s", rule.Source))
	}
	parts = append(parts, rule.Action)

	ruleStr := ""
	for i, p := range parts {
		if i > 0 {
			ruleStr += " "
		}
		ruleStr += p
	}

	return nftRule{Rule: ruleStr, Comment: fmt.Sprintf("input from %s zone", rule.Zone)}
}
