package unbound

import (
	"bytes"
	"fmt"
	"net"
	"text/template"

	"github.com/fdcastel/warp-router/internal/config"
)

const unboundConfTemplate = `# Warp Router — Unbound DNS resolver configuration
# Generated by 'warp apply'. Do not edit manually.

server:
    verbosity: 1
{{- range .ListenAddresses }}
    interface: {{ . }}
{{- end }}

    # Access control
    access-control: 127.0.0.0/8 allow
    access-control: ::1/128 allow
{{- range .AllowFrom }}
    access-control: {{ . }} allow
{{- end }}

    # Performance
    num-threads: 2
    msg-cache-slabs: 4
    rrset-cache-slabs: 4
    infra-cache-slabs: 4
    key-cache-slabs: 4
    msg-cache-size: 64m
    rrset-cache-size: 128m

    # Privacy and security
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-referral-path: yes
    use-caps-for-id: yes

    # Prefetch
    prefetch: yes
    prefetch-key: yes

    # Root hints
    root-hints: "/usr/share/dns/root.hints"

    # Trust anchor for DNSSEC
    auto-trust-anchor-file: "/var/lib/unbound/root.key"
{{- if .Forwarders }}

forward-zone:
    name: "."
{{- range .Forwarders }}
    forward-addr: {{ . }}
{{- end }}
{{- end }}
`

type unboundData struct {
	ListenAddresses []string
	AllowFrom       []string
	Forwarders      []string
}

// Render generates unbound.conf from the site config.
func Render(cfg *config.SiteConfig) (string, error) {
	data := unboundData{
		ListenAddresses: []string{"127.0.0.1", "::1"},
	}

	// Collect LAN interface IPs for listening and access control
	var lanSubnets []string
	for _, iface := range cfg.Interfaces {
		if iface.Role == "lan" && iface.Address != "" && iface.Address != "dhcp" {
			ip, ipnet, err := net.ParseCIDR(iface.Address)
			if err == nil {
				data.ListenAddresses = append(data.ListenAddresses, ip.String())
				lanSubnets = append(lanSubnets, ipnet.String())
			}
		}
	}

	// Access control
	if cfg.DNS != nil && len(cfg.DNS.AllowFrom) > 0 {
		data.AllowFrom = cfg.DNS.AllowFrom
	} else {
		data.AllowFrom = lanSubnets
	}

	// Listen addresses override
	if cfg.DNS != nil && len(cfg.DNS.Listen) > 0 {
		data.ListenAddresses = cfg.DNS.Listen
	}

	// Forwarders
	if cfg.DNS != nil && len(cfg.DNS.Forwarders) > 0 {
		data.Forwarders = cfg.DNS.Forwarders
	}

	tmpl, err := template.New("unbound.conf").Parse(unboundConfTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing Unbound template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing Unbound template: %w", err)
	}

	return buf.String(), nil
}
